sandbox/sail: Added sctk patch.
This patch adds -ffreestanding flag to the compile flags for rfilter1 to
silence the following error thrown by recent c++ compilers.

rfilter1.c:29:5:
error: second parameter of 'main' (argument array) must be of type 'char **'
int main(int argc, char **argv)
    ^

There is a nasty typedef @ tools/sctk-2.4.0/src/rfilter1/include/stdcenvp.h:27
which maps char to unsigned char. This is supposed to be a hack for parsing
mandarin and japanese correctly. However, that typedef causes all chars in all
files including that header file to be mapped to unsigned char. While most
such mappings are benign, we have one problematic case which results in the
compiler error given above.